version: '3'

services:
  nest-backend:
    container_name: nest-app
    image: nest-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5001:5000
    env_file:
      - .env.dev
    networks:
      - backend_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres
      - redis

  redis:
    container_name: redis-db
    image: redis
    env_file:
      - .env.dev
    ports:
      - 16379:6379
    networks:
      - backend_network
    volumes:
      - redis:/data

  postgres:
    container_name: postgres-db
    image: postgres:15
    ports:
      - 15432:5432
    env_file:
      - .env.dev
    networks:
      - backend_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/dbDumpFile:/dbDumpFile
      - /var/run/docker.sock:/var/run/docker.sock

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    networks:
      - backend_network
    ports:
      - '5050:80'
    depends_on:
      - postgres

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data: {}
  redis:
    driver: local
