version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - app-network

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
