name: unified-fc-backend-deployment-docker-compose

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CONTABO_HOST }}
          username: ${{ secrets.CONTABO_USERNAME }}
          key: ${{ secrets.CONTABO_SSH_KEY }}
          script: |
            cd ~/unified-fc-backend
            git pull origin dev
            docker-compose --env-file .env.prod -f docker-compose.prod.yml up --build -d
